local Rayfield = loadstring(game:HttpGet('https://raw.githubusercontent.com/shlexware/Rayfield/main/source'))()
getgenv().SecureMode = true
local Window = Rayfield:CreateWindow({
    Name = "Gitlernamer",
    LoadingTitle = "yarik top",
    LoadingSubtitle = "Lin pidor",
    ConfigurationSaving = {
       Enabled = true,
       FolderName = nil, -- Create a custom folder for your hub/game
       FileName = "AnusSex"
    },
    Discord = {
       Enabled = true,
       Invite = "noinvitelink", -- The Discord invite code, do not include discord.gg/. E.g. discord.gg/ABCD would be ABCD.
       RememberJoins = true -- Set this to false to make them join the discord every time they load it up
    },
    KeySystem = false, -- Set this to true to use our key system
    KeySettings = {
       Title = "X3rL3 Hub",
       Subtitle = "Key System",
       Note = "Buy me",
       FileName = "X3rL3Key",
       SaveKey = true,
       GrabKeyFromSite = false, -- If this is true, set Key below to the RAW site you would like Rayfield to get the key from
       Key = "askodfasknfasjkonfasnfansfvnabn,penis",
       Key = "sexxygitler"
    }
 })

 local Tab = Window:CreateTab("Main", 4483362458) -- Title, Image
 local Section = Tab:CreateSection("Main Stuff")

 local Button = Tab:CreateButton({
    Name = "tp to secret pos",
    Callback = function()
        local teleport_table = {
            location1 = Vector3.new(91.6054077, 696.557373, 983.817505, 1, 0, 0, 0, 1, 0, 0, 0, 1), -- your desired position
            location2 = Vector3.new()  -- your desired position
        }
        
        local tween_s = game:GetService('TweenService')
        local tweeninfo = TweenInfo.new(1,Enum.EasingStyle.Linear)
        
        local lp = game.Players.LocalPlayer
        
        function bypass_teleport(v)
            if lp.Character and 
            lp.Character:FindFirstChild('HumanoidRootPart') then
                local cf = CFrame.new(v)
                local a = tween_s:Create(lp.Character.HumanoidRootPart,tweeninfo,{CFrame=cf})
                a:Play()
                -- a.Completed:Wait()
                -- print('Teleporting Done!')
            end
        end
        
        bypass_teleport(teleport_table.location1)
    end,
 })

 local Button = Tab:CreateButton({
    Name = "Button Example",
    Callback = function()
    -- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = "TSRubber"
local A_2 = "JetPistol"
local A_3 = 
{
}
local Event = game:GetService("ReplicatedStorage").ReplicatorNoYield
Event:FireServer(A_1, A_2, A_3)

-- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = "TSRubber"
local A_2 = "JetGatling"
local A_3 = 
{
	["MouseRay"] = 
{
	["Normal"] = Vector3.new(-0.5681984424591064, 0.002794921398162842, -0.8228868246078491), 
	["Direction"] = Vector3.new(205.0072021484375, -159.16107177734375, 150.46531677246094), 
	["Origin"] = Vector3.new(16.544527053833008, 798.7542724609375, 931.00146484375), 
	["Instance"] = game:GetService("Workspace").Terrain.Tree2.Leaves, 
	["Distance"] = 68.14972686767578, 
	["Position"] = Vector3.new(63.11515808105469, 762.5983276367188, 965.1820068359375), 
	["Material"] = Enum.Material.Grass
}
}
local Event = game:GetService("ReplicatedStorage").ReplicatorNoYield
Event:FireServer(A_1, A_2, A_3)


    end,
 })
-----(Pm)
local Tab = Window:CreateTab("Project Mugetsu Stuff", 4483362458) -- Title, Image
local Section = Tab:CreateSection("Piska111111")

local Button = Tab:CreateButton({
    Name = "Esp(btw white color",
    Callback = function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/Lucasfin000/SpaceHub/main/UESP'))()
    end,
 })

 local Button = Tab:CreateButton({
    Name = "Small server finder yey",
    Callback = function()
    --[[
	
]]
local Http = game:GetService("HttpService")
local TPS = game:GetService("TeleportService")
local Api = "https://games.roblox.com/v1/games/"

local _place = game.PlaceId
local _servers = Api.._place.."/servers/Public?sortOrder=Asc&limit=100"
function ListServers(cursor)
   local Raw = game:HttpGet(_servers .. ((cursor and "&cursor="..cursor) or ""))
   return Http:JSONDecode(Raw)
end

local Server, Next; repeat
   local Servers = ListServers(Next)
   Server = Servers.data[1]
   Next = Servers.nextPageCursor
until Server

TPS:TeleportToPlaceInstance(_place,Server.id,game.Players.LocalPlayer)
    end,
 })

 local Button = Tab:CreateButton({
    Name = "Get quest for Become HOLLOW",
    Callback = function()
        local args = {
            [1] = "Aizen",
            [2] = "Add"
        }
        
        game:GetService("ReplicatedStorage"):WaitForChild("Remotes"):WaitForChild("Quest_Remote"):FireServer(unpack(args))
    end,
 })

 local Button = Tab:CreateButton({
    Name = "Get quest for BECOME A SHINIGAMI",
    Callback = function()
        local args = {
            [1] = "Kisuke",
            [2] = "Add"
        }
        
        game:GetService("ReplicatedStorage"):WaitForChild("Remotes"):WaitForChild("Quest_Remote"):FireServer(unpack(args))
    end,
 })

 local Button = Tab:CreateButton({
    Name = "Tp to 1-10 lvl quest",
    Callback = function()
    game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-800.4718017578125, 3.1741461753845215, 39.24939727783203)
    end,
 })

 local Button = Tab:CreateButton({
    Name = "Trash quest (350 gold total)",
    Callback = function()
    game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-729.39794921875, 3.1748297214508057, -326.10931396484375)
    end,
 })

 local Button = Tab:CreateButton({
    Name = "Very good script (10-20 lvl)",
    Callback = function()
    game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-151.80227661132812, 3.0257010459899902, -519.0812377929688)
    end,
 })
--Auto spinner(cuz im gay)
local Toggle = Tab:CreateToggle({
   Name = "Spin (all myth, all war penis!#",
   CurrentValue = false,
   Flag = "Toggle1", -- A flag is the identifier for the configuration file, make sure every element has a different flag if you're using configuration saving to ensure no overlaps
   Callback = function(Value)
      repeat wait() until game:IsLoaded()
    wait(2)
    local clans = {"Uryu", "Yamamoto", "Urahara", "Kurosaki"}
    local url = "webhook"

    game:GetService("ReplicatedStorage").Change_Slot:InvokeServer(1) --change slot here, 1 for 1st slot, 2 for 2nd

    function redeem()
        local a = {"35KLIKES", "SORRYFORSHUTDOWN", "RELEASE", "EXPLOITFIXES", "SHUTDOWNSPINS","SORRYFORPINGS","10MVISITS","50KLIKES","SHUTDOWNABILITYREROLL","40KLIKES"}

        for _, itemName in pairs(a) do
            game:GetService("ReplicatedStorage").Code:InvokeServer(itemName)
        end
    end

    redeem()
    wait(2)

    function spin()
        local user = tostring(game.Players.LocalPlayer)

        while true do
            game:GetService("ReplicatedStorage").Spin:InvokeServer(1)
            task.wait(0.1)
            local found = false

            for i=1, #clans do
                if clans[i]:lower() == game:GetService("ReplicatedStorage")["Player_Datas"][user]["Slot_1"].Clan.Value:lower() then
                    found = true
                    break
                end
            end

            if found then
                print("YAYYYYY YOU GOT "..tostring(game:GetService("ReplicatedStorage")["Player_Datas"][user]["Slot_1"].Clan.Value))
                local data = {
                    ["content"] = "@everyone YOU ROLLED SOMETHING",
                    ["username"] = "Jon Jones",
                    ["avatar_url"] = "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2335639.png",
                    ["embeds"] = {
                        {
                            ["description"] = "**Project Mugetsu**\n\n```User: "..user.."\n\nClan: "..game:GetService("ReplicatedStorage")["Player_Datas"][user]["Slot_1"].Clan.Value.."```",
                            ["type"] = "rich",
                            ["color"] = tonumber(0x5a3812)
                        }
                    }
                }
                local newdata = game:GetService("HttpService"):JSONEncode(data)
                local headers = {
                    ["content-type"] = "application/json"
                }
                request = http_request or request or HttpPost or syn.request
                local send = {Url = url, Body = newdata, Method = "POST", Headers = headers}
                request(send)
                break
            else
                print("Rolled "..tostring(game:GetService("ReplicatedStorage")["Player_Datas"][user]["Slot_1"].Clan.Value))
            end
        end
    end

    spin()
   -- The variable (Value) is a boolean on whether the toggle is true or false
   end,
})
      

-----Pm Quest mb risk
local Tab = Window:CreateTab("PM (MB RISKY)", 4483362458) -- Title, Image
local Section = Tab:CreateSection("Pm Auto quest")

local Button = Tab:CreateButton({
   Name = "Painless quest (ping me if patched)",
   Callback = function()
      local args = {
         [1] = "Painless",
         [2] = "Add"
     }
     
     game:GetService("ReplicatedStorage"):WaitForChild("Remotes"):WaitForChild("Quest_Remote"):FireServer(unpack(args))
   end,
})

local Button = Tab:CreateButton({
   Name = "1-10 lvl auto quest(mb patched dont care)",
   Callback = function()
      local args = {
         [1] = "Baloish",
         [2] = "Add"
     }
     
     game:GetService("ReplicatedStorage"):WaitForChild("Remotes"):WaitForChild("Quest_Remote"):FireServer(unpack(args))
   end,
})
-----PM QUEST(PARAGRAPH)
local Paragraph = Tab:CreateParagraph({Title = "Soul cock soccer", Content = "Only IN SOUL COCKER OR YOU WILL GET BAN"})

local Button = Tab:CreateButton({
   Name = "Biscuit",
   Callback = function()
      local args = {
         [1] = "Biscuit",
         [2] = "Add"
     }
     
     game:GetService("ReplicatedStorage"):WaitForChild("Remotes"):WaitForChild("Quest_Remote"):FireServer(unpack(args))
   end,
})

local Button = Tab:CreateButton({
   Name = "Kounde",
   Callback = function()
      local args = {
         [1] = "Kounde",
         [2] = "Add"
     }
     
     game:GetService("ReplicatedStorage"):WaitForChild("Remotes"):WaitForChild("Quest_Remote"):FireServer(unpack(args))
   end,
})

local Button = Tab:CreateButton({
   Name = "Ichigo",
   Callback = function()
   game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(4385.8388671875, 12.715703964233398, -3334.48046875)
   end,
})

local Button = Tab:CreateButton({
   Name = "Huyuakiya",
   Callback = function()
   game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(1929.16357421875, 26.344667434692383, -3377.259521484375)
   end,
})

local Button = Tab:CreateButton({
   Name = "Better Script than my",
   Callback = function()
   loadstring(game:HttpGet("https://raw.githubusercontent.com/XO-3S-CL-VCK-jf-3HDM/Products/main/Project-Mugetsu.lua"))()
   end,
})
---Local player
local Tab = Window:CreateTab("Local Player", 4483362458) -- Title, Image
local Section = Tab:CreateSection("Walkspeed + jump modify")

local Slider = Tab:CreateSlider({
   Name = "Speed",
   Range = {0, 75},
   Increment = 10,
   Suffix = "Bananas",
   CurrentValue = 10,
   Flag = "Slider1", -- A flag is the identifier for the configuration file, make sure every element has a different flag if you're using configuration saving to ensure no overlaps
   Callback = function(Value)
   game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = 75
   end,
})





















































Rayfield:LoadConfiguration()
